Configurable maximum cache size
mopidy/mopidy-spotify pull request #356
Opened 2023-04-15 01:30 UTC by beaverking1212

Configurable maximum cache size with 8 GiB default.

2023-04-15 09:41 UTC, kingosticks requested changes

2023-04-15 17:41 UTC, beaverking1212 commented on README.rst
> +- ``spotify/cache_size``: maximum cache size in MiB. Defaults to ``8192``.
I think the default should be a constant. Here is a table with approximate cache size in songs and hours. I think the everyday music library should fit in the cache for the cache to be efficient.
| Cache size | Approx. hours 320 kbps | Approx. songs 320 kbps | Approx. hours 160 kbps | Approx. songs 160 kbps | 
|-----|-----|-----|-----|-----|
| 8192 MB |59 h|889 songs|118 h|1778 songs|
| 4096 MB |30 h|444 songs|59 h|889 songs|
| 2048 MB |15 h|222 songs|30 h|444 songs|

Should the default be 4096, 2048 or some other size?

2023-04-15 19:43 UTC, beaverking1212 commented
Tests fixed and readme changed as requested.

2023-04-15 22:42 UTC, kingosticks approved these changes

2023-04-15 22:43 UTC, merged

2023-04-15 22:46 UTC, kingosticks commented
Let's go with 8GB for now, there's no one-size fits all answer and it's clearly documented for adjusting. thanks!

2023-04-16 02:55 UTC, beaverking1212 commented
Thank you!